apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calculator-app    # keep consistent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: calculator-app  # must match labels below exactly
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: calculator-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort | default 8080 }}
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 10 }}
