apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  namespace: calculator
  annotations:
    argocd.argoproj.io/tracking-id: calculator-app:apps/Deployment:calculator/calculator-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
