apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RAHUL-AMBARAGONDA/your-repo.git
    targetRevision: main
    path: charts/calculator-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
