# calculator-app/charts/calculator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: calculator
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
