apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  namespace: default
  labels:
    app: calculator-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: calculator-container
          image: rahulambaragonda/calculator-app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /

              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /

              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

