apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  labels:
    app: calculator-app
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
