name: Build and Push Calculator Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITOPS_REPO: RAHUL-AMBARAGONDA/devops-team
      GITOPS_REPO_DIR: ./devops-team
      GITOPS_REPO_BRANCH: main
      VALUES_FILE: charts/calculator/values/dev.yaml

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
         docker build -t rahulambaragonda/calculator:v1.5 .
         docker push rahulambaragonda/calculator:v1.5

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: ${{ env.GITOPS_REPO_BRANCH }}
          path: ${{ env.GITOPS_REPO_DIR }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Helm values image tag
        run: |
          cd $GITOPS_REPO_DIR
          yq eval ".image.tag = \"$IMAGE_TAG\"" -i $VALUES_FILE
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"
          git add $VALUES_FILE
          git diff --quiet || (git commit -m "chore: update calculator image tag to $IMAGE_TAG" && git push origin $GITOPS_REPO_BRANCH)

      - name: Done
        run: echo "✅ Image pushed and GitOps repo updated"
