name: Build and Push Calculator Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        IMAGE_TAG=calculator-$(date +%s)
        docker build -t rahulambaragonda/calculator:$IMAGE_TAG .
        docker push rahulambaragonda/calculator:$IMAGE_TAG
        echo "Pushed image: rahulambaragonda/calculator:$IMAGE_TAG"

    - name: Trigger Argo CD Image Updater (if needed)
      run: echo "No action needed — image updater will auto-detect the new tag."
